name: ExampleTransferPlugin
version: '${project.version}'
main: dev.codedred.exampletransferplugin.ExampleTransferPlugin
api-version: 1.17
authors: [ WorldQL ]
description: Example usage for the server transfer mod
website: worldql.com
depend: [server-transfer-plugin]

commands:
  connect: {}
