name: Java Build
on:
  push:
    branches:
      - trunk
    tags:
      - v*
  pull_request:

env:
  JDK_VERSION: '17'
  SPIGOT_VERSION: '1.18.2'

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ env.JDK_VERSION }}
        cache: maven
    - name: Build with Maven
      working-directory: ./server-transfer-plugin
      run: mvn -B package --file pom.xml
    - name: Resolve .jar name
      id: prep
      run: |
        JAR_PATH=`echo ServerTransferPlugin/target/server-transfer-plugin*.jar`
        JAR_NAME=`basename ${JAR_PATH}`

        VERSION=`git rev-parse --short HEAD`
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        fi

        echo ::set-output name=jar_path::${JAR_PATH}
        echo ::set-output name=jar_name::${JAR_NAME}
        echo ::set-output name=version::${VERSION}
    - name: Upload .jar
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.prep.outputs.jar_name }}
        path: ${{ steps.prep.outputs.jar_path }}
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Server Transfer ${{ steps.prep.outputs.version }}
        files: ${{ steps.prep.outputs.jar_path }}
        generate_release_notes: true

  build-mod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ env.JDK_VERSION }}
        cache: gradle
    - name: Build with Gradle
      working-directory: ./server-transfer-mod
      run: ./gradlew build --no-daemon
    - name: Resolve .jar name
      id: prep
      run: |
        JAR_PATH=`echo ServerTransferMod/build/libs/server-transfer-mod*[^sources].jar`
        JAR_NAME=`basename ${JAR_PATH}`

        VERSION=`git rev-parse --short HEAD`
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        fi

        echo ::set-output name=jar_path::${JAR_PATH}
        echo ::set-output name=jar_name::${JAR_NAME}
        echo ::set-output name=version::${VERSION}
    - name: Upload .jar
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.prep.outputs.jar_name }}
        path: ${{ steps.prep.outputs.jar_path }}
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Server Transfer ${{ steps.prep.outputs.version }}
        files: ${{ steps.prep.outputs.jar_path }}
        generate_release_notes: true
